version: '3'
services:
  gpt-researcher:
<<<<<<< HEAD
    container_name: vv-gpt-researcher
    build: 
      context: ./
      dockerfile: Dockerfile.Dev
    ports:
      - 8010:8000
      - 3002:3002
    volumes:
      - "./:/usr/src/app/"
    env_file:
      - .env
    networks:
      - valorai-external-network

networks:
  valorai-external-network:
    external: true
=======
    pull_policy: build
    image: gptresearcher/gpt-researcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
    restart: always
    ports:
      - 8000:8000
  gptr-nextjs:
    pull_policy: build
    image: gptresearcher/gptr-nextjs
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: multi_agents/frontend
    volumes:
      - /app/node_modules
      - ./multi_agents/frontend:/app
    restart: always
    ports:
      - 3000:3000
>>>>>>> master
