services:
  gpt-researcher:
    pull_policy: build
    image: gptresearcher/gpt-researcher
    container_name: gr-server
    build: 
      context: .
      dockerfile: Dockerfile.Ext
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
    restart: always
    ports:
      - 8000:8000
  gptr-nextjs:
    pull_policy: build
    image: gptresearcher/gptr-nextjs
    container_name: gr-client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: frontend/nextjs
    volumes:
      - /app/node_modules
      - ./frontend/nextjs:/app
    restart: always
    ports:
      - 3000:3000
  caddy:
    image: caddy:2-alpine
    container_name: gr-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile-prod:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./frontend/nextjs/public:/usr/share/caddy
    depends_on:
      - gpt-researcher
      - gptr-nextjs